Repository googleapis/java-pubsublite-kafka, pull requests merged in 2020-12, with the labels that each got.

#31 fix(readme): update readme snippets
  README.md
Labels: api: pubsublite, cla: yes

#34 chore: Update publish_javadoc.sh
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: api: pubsublite, automerge, cla: yes, context: full

#33 samples: add producer and consumer samples
  .kokoro/continuous/java11-samples.cfg
  .kokoro/continuous/java8-samples.cfg
  .kokoro/nightly/java7.cfg
  .kokoro/nightly/samples.cfg
  .kokoro/presubmit/java7.cfg
  .kokoro/presubmit/samples.cfg
  .kokoro/run_samples_tests.sh
  samples/pom.xml
  samples/snapshot/pom.xml
  samples/snippets/pom.xml
  samples/snippets/src/main/java/pubsublite/ConsumerExample.java
  samples/snippets/src/main/java/pubsublite/ProducerExample.java
  samples/snippets/src/test/java/pubsublite/QuickStartIT.java
Labels: api: pubsublite, cla: yes, samples

#36 chore: regenerate common templates
  .kokoro/nightly/java7.cfg
  .kokoro/nightly/samples.cfg
  .kokoro/presubmit/java7.cfg
  .kokoro/presubmit/samples.cfg
  synth.metadata
Labels: api: pubsublite, automerge, cla: yes, context: none

#38 ci(java): ignore bot users for generate-files-bot
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: pubsublite, automerge, cla: yes, context: full

#37 feat: Add support for increasing partitions to the kafka shim
  pom.xml
  src/main/java/com/google/cloud/pubsublite/kafka/ConsumerSettings.java
  src/main/java/com/google/cloud/pubsublite/kafka/ProducerSettings.java
  src/main/java/com/google/cloud/pubsublite/kafka/PubsubLiteConsumer.java
  src/main/java/com/google/cloud/pubsublite/kafka/PubsubLiteProducer.java
  src/main/java/com/google/cloud/pubsublite/kafka/SharedBehavior.java
  src/test/java/com/google/cloud/pubsublite/kafka/PubsubLiteConsumerTest.java
  src/test/java/com/google/cloud/pubsublite/kafka/PubsubLiteProducerTest.java
  src/test/java/com/google/cloud/pubsublite/kafka/SharedBehaviorTest.java
Labels: api: pubsublite, cla: yes

#42 chore(java): remove formatter action
  .github/workflows/formatting.yaml
  synth.metadata
Labels: api: pubsublite, cla: yes, context: full
