Repository googleapis/java-pubsublite-kafka, pull requests merged in 2020-11, with the labels that each got.

#10 chore: update Automation
  .readme_partials.yaml
  synth.py
Labels: api: pubsublite, cla: yes

#15 chore: Update .repo-metadata.json
  .repo-metadata.json
Labels: api: pubsublite, cla: yes

#17 fix: Start assigner when subscribe() is called
  src/main/java/com/google/cloud/pubsublite/kafka/PubsubLiteConsumer.java
  src/test/java/com/google/cloud/pubsublite/kafka/PubsubLiteConsumerTest.java
Labels: api: pubsublite, cla: yes

#14 [CHANGE ME] Re-generated to pick up changes in the API or client library generator.
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/generated-files-bot.yml
  .github/workflows/formatting.yaml
  .github/workflows/samples.yaml
  .kokoro/build.sh
  .kokoro/nightly/samples.cfg
  .kokoro/presubmit/samples.cfg
  .kokoro/readme.sh
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  .kokoro/release/stage.cfg
  CODE_OF_CONDUCT.md
  renovate.json
  samples/install-without-bom/pom.xml
  samples/pom.xml
  samples/snapshot/pom.xml
  samples/snippets/pom.xml
  synth.metadata
Labels: api: pubsublite, cla: yes

#18 build(java): use actions/github-script v3 tag rather than full semver
  .github/workflows/approve-readme.yaml
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: pubsublite, cla: yes, context: full

#20 docs: Update README.md
  README.md
Labels: api: pubsublite, cla: yes

#21 chore(java): retry staging portion of the release with backoff
  .kokoro/common.sh
  .kokoro/release/stage.sh
  synth.metadata
Labels: api: pubsublite, automerge, cla: yes, context: full

#22 build(java): enable blunderbuss for samples
  .github/blunderbuss.yml
  synth.metadata
Labels: api: pubsublite, automerge, cla: yes, context: full, samples
