Repository googleapis/java-pubsublite-kafka, pull requests merged in 2021-01, with the labels that each got.

#47 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsublite, automerge, cla: yes

#48 docs: rename .readme_partials to .readme-partials
  .readme-partials.yaml
Labels: api: pubsublite, cla: yes

#49 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsublite, automerge, cla: yes

#53 fix: Incorrect exception handling exposed by underlying API translating ExecutionException differently
  pom.xml
  src/test/java/com/google/cloud/pubsublite/kafka/SharedBehaviorTest.java
Labels: api: pubsublite, cla: yes

#52 chore: adding docfx doclet resource
  .kokoro/release/publish_javadoc.cfg
  synth.metadata
Labels: api: pubsublite, cla: yes, context: full

#54 docs: update readme source files
  .readme-partials.yaml
  .repo-metadata.json
  samples/snippets/pom.xml
Labels: api: pubsublite, cla: yes

#55 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsublite, automerge, cla: yes

#57 build: migrate to flakybot
  .kokoro/build.sh
Labels: api: pubsublite, automerge, cla: yes
