Repository googleapis/java-pubsublite-kafka, pull requests merged in 2021-02, with the labels that each got.

#64 chore: Re-generated to pick up changes from synthtool.
  .github/workflows/ci.yaml
  .kokoro/linkage-monitor.sh
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc11.cfg
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: pubsublite, cla: yes, context: partial

#66 chore: Re-generated to pick up changes from synthtool
  .github/workflows/auto-release.yaml
  LICENSE
  synth.metadata
Labels: api: pubsublite, automerge, cla: yes, context: full

#67 fix: update repo name
  .kokoro/release/publish_javadoc11.cfg
  synth.metadata
Labels: api: pubsublite, cla: yes, context: full

#69 build(java): update autorelease script
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: pubsublite, automerge, cla: yes, context: full

#71 ci: linkage monitor CI job to use build.sh
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: pubsublite, automerge, cla: yes, context: full

#72 chore: update cloud-rad buckets
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  .kokoro/release/publish_javadoc11.cfg
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: pubsublite, automerge, cla: yes, context: full

#73 build: skip Maven download logs
  .kokoro/build.sh
  synth.metadata
Labels: api: pubsublite, automerge, cla: yes, context: full

#74 build: reduce download junk in log files
  .kokoro/build.sh
  .kokoro/dependencies.sh
  synth.metadata
Labels: api: pubsublite, automerge, cla: yes, context: full

#77 docs: update client library documentation link
  .repo-metadata.json
Labels: api: pubsublite, cla: yes

#78 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsublite, automerge, cla: yes

#79 deps: Bump underlying pub/sub lite version to 0.11.0
  pom.xml
  src/main/java/com/google/cloud/pubsublite/kafka/ConsumerSettings.java
  src/main/java/com/google/cloud/pubsublite/kafka/ProducerSettings.java
  src/main/java/com/google/cloud/pubsublite/kafka/PubsubLiteProducer.java
  src/test/java/com/google/cloud/pubsublite/kafka/PubsubLiteProducerTest.java
Labels: api: pubsublite, cla: yes
