Repository googleapis/java-pubsublite-kafka, pull requests merged in 2021-08, with the labels that each got.

#166 build: configure branch java7 as a release branch
  .github/release-please.yml
  .github/sync-repo-settings.yaml
Labels: api: pubsublite, automerge, cla: yes

#168 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsublite, automerge, cla: yes

#170 deps: version bump underlying pubsub lite library
  pom.xml
  src/main/java/com/google/cloud/pubsublite/kafka/ConsumerSettings.java
  src/main/java/com/google/cloud/pubsublite/kafka/ProducerSettings.java
  src/main/java/com/google/cloud/pubsublite/kafka/RecordTransforms.java
  src/main/java/com/google/cloud/pubsublite/kafka/SingleSubscriptionConsumerImpl.java
Labels: api: pubsublite, cla: yes

#167 chore: configure initial java7 version
  .github/workflows/ci.yaml
Labels: api: pubsublite, automerge, cla: yes

#174 feat: Add setTopicPathOverride to consumer settings
  clirr-ignored-differences.xml
  src/main/java/com/google/cloud/pubsublite/kafka/ConsumerSettings.java
Labels: cla: yes, api: pubsublite

#177 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes, api: pubsublite

#182 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes, api: pubsublite

#172 feat: Reset Consumer upon out-of-band seek
  .readme-partials.yaml
  src/main/java/com/google/cloud/pubsublite/kafka/ConsumerSettings.java
  src/main/java/com/google/cloud/pubsublite/kafka/PullSubscriberFactory.java
  src/main/java/com/google/cloud/pubsublite/kafka/SinglePartitionSubscriber.java
  src/main/java/com/google/cloud/pubsublite/kafka/SingleSubscriptionConsumerImpl.java
  src/test/java/com/google/cloud/pubsublite/kafka/SinglePartitionSubscriberTest.java
  src/test/java/com/google/cloud/pubsublite/kafka/SingleSubscriptionConsumerImplTest.java
Labels: cla: yes, api: pubsublite

#184 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes, api: pubsublite

#189 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes, api: pubsublite

#197 fix: Fail hard in subscribe() call on assignment failure
  src/main/java/com/google/cloud/pubsublite/kafka/PubsubLiteConsumer.java
  src/test/java/com/google/cloud/pubsublite/kafka/PubsubLiteConsumerTest.java
Labels: cla: yes, api: pubsublite

#196 build(java): use ENABLE_FLAKYBOT env variable
  .kokoro/build.sh
  .kokoro/nightly/integration.cfg
  .kokoro/nightly/samples.cfg
  synth.metadata
Labels: cla: yes, api: pubsublite, context: full

#199 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes, api: pubsublite

#202 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes, api: pubsublite

#203 ci: removing linkage-monitor from the required checks
  .github/sync-repo-settings.yaml
Labels: automerge, cla: yes, api: pubsublite
