Repository googleapis/java-pubsublite-kafka, pull requests merged in 2021-09, with the labels that each got.

#205 ci: removing linkage-monitor from the required checks
  .github/workflows/ci.yaml
  synth.metadata
Labels: automerge, cla: yes, api: pubsublite, context: full

#210 chore: regenerate common templates
  .github/readme/synth.py
  .github/trusted-contribution.yml
  .github/workflows/ci.yaml
  .kokoro/continuous/readme.cfg
  .kokoro/release/common.sh
  .kokoro/release/drop.sh
  .kokoro/release/promote.sh
  .kokoro/release/publish_javadoc.sh
  .kokoro/release/publish_javadoc11.sh
  .kokoro/release/stage.sh
  .kokoro/trampoline.sh
  renovate.json
  synth.metadata
Labels: cla: yes, api: pubsublite, context: full

#228 chore: remove readme autosynth config
  .github/readme/synth.metadata/synth.metadata
Labels: automerge, cla: yes, api: pubsublite

#233 chore: change branch master to main in github configurations
  .github/sync-repo-settings.yaml
Labels: automerge, cla: yes, api: pubsublite
