Repository googleapis/java-pubsublite-kafka, pull requests merged in 2021-03, with the labels that each got.

#82 fix: Add admin client in producer settings
  src/main/java/com/google/cloud/pubsublite/kafka/ProducerSettings.java
Labels: api: pubsublite, cla: yes

#84 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsublite, automerge, cla: yes

#92 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsublite, automerge, cla: yes

#94 chore: remove docLava v2 doc generation
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: api: pubsublite, cla: yes, context: full

#95 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsublite, automerge, cla: yes

#96 fix: Add default batching in producer settings
  src/main/java/com/google/cloud/pubsublite/kafka/ProducerSettings.java
Labels: api: pubsublite, cla: yes

#99 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: pubsublite, automerge, cla: yes

#100 chore: copy README to docfx-yml dir
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: pubsublite, automerge, cla: yes, context: full

#101 build(java): update autorelease title check in response to the new multi release branch changes
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: pubsublite, cla: yes, context: full

#102 feat: Implement Consumer.endOffsets
  src/main/java/com/google/cloud/pubsublite/kafka/ConsumerSettings.java
  src/main/java/com/google/cloud/pubsublite/kafka/PubsubLiteConsumer.java
  src/test/java/com/google/cloud/pubsublite/kafka/PubsubLiteConsumerTest.java
Labels: api: pubsublite, cla: yes

#107 chore(java): detect sample-secrets in build.sh
  .kokoro/build.sh
  synth.metadata
Labels: api: pubsublite, build.sh, cla: yes, context: full, in, sample-secrets, samples

#108 chore: remove staging bucket v2
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: api: pubsublite, automerge, cla: yes, context: full
